faq/urls.py
from django.urls import path

from . import views

app_name='faq'

urlpatterns = [
    path("", views.faq_index, name="faq_index")
]

faq/models.py
from django.db import models

# Create your models here.

faq/views.py
from django.shortcuts import render

# Create your views here.
def faq_index(request):
    context={

    }
    return render(request, 'faq/faq.html',context)

faq/templates/faq/faq.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title> FAQ</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'faq/faqs.css' %}"> 


</head>
<body>

    <div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="active link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>

    <section id="showcase">
		<div class="container">
			<img src="{% static 'faq/faq.jpg' %}">
		</div>
	</section>

    <div class="heading">
        <h1> Frequently Asked Questions(FAQs)</h1>
   </div>

   <hr class="sep">
   
<section id="ques">
<div class="container">
   <div class="box">
        <div class="subbox" >
             <details>
                 <summary class="question">This is the Question no 1?</a></summary>
                 <p class="text"> This is the answer for question 1</p>
             </details>
        </div>    

        <div class="subbox">
             <details>
                 <summary class="question">This is the Question no 2?</summary>
                 <p class="text"> This is the answer for question 2</p>
             </details>
        </div>

        <div class="subbox">
             <details>
                 <summary class="question">This is the Question no 3?</summary>
                 <p class="text"> This is the answer for question 3</p>
             </details>
        </div>

        <div class="subbox">
             <details>
                 <summary class="question">This is the Question no 4?</summary>
                 <p class="text"> This is the answer for question 4</p>
             </details>
        </div>

   </div>
</div>
</section>

<footer class="footer-distributed">
 
    <div class="footer-left">
    
    <h3><span class="highlight">Elite</span>Rental</h3>
    
    <p class="footer-links">
    <a href="">Home</a>
    ·
    <a href="#">Services</a>
    ·
    <a href="#">Contact</a>
    ·
    <a href="#">About</a>
    ·
    <a href="#">Faq</a>

    </p>
    
    <p class="footer-company-name">eliterental &copy; 2021</p>
    </div>
    
    <div class="footer-center">
    
    <div>
    <i class="fa fa-map-marker"></i>
    <p><span>Dillibazar</span> Kathmandu, Nepal</p>
    </div>
    
    <div>
    <i class="fa fa-phone"></i>
    <p>+1 555 123456</p>
    </div>
    
    <div>
    <i class="fa fa-envelope"></i>
    <p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
    </div>
    
    </div>
    
    <div class="footer-right">
    
    <p class="footer-company-about">
    <span>About the company</span>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </p>
    
    <div class="footer-icons">
    
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
    
    </div>
    
    </div>
    
    </footer>


  

</body>
</html>