accounts/urls.py
from django.urls.conf import include
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    path("register", views.register, name="register"),
    path("login", views.loginPage, name="loginPage"),
    path("logout", views.logoutUser, name="logout"),
    path("success", views.success, name="success"),
    path("profile", views.userProfile,name="profile")
]

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class UserAddress(models.Model):
    country_choices=(
    ("Nepal","Nepal"),
    )

    user_info= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)   
    address = models.CharField(max_length=150)
    street = models.CharField(max_length=150)
    postalcode = models.CharField(max_length=10)
    city = models.CharField(max_length=150)
    country = models.CharField(max_length=150, choices=country_choices, default='Nepal')
    
    def __str__(self):
        return f'{self.user_info.id} -- {self.user_info.first_name} {self.user_info.last_name} -- {self.user_info.email}'
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields =['first_name', 'last_name','username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.conf import settings

from .models import UserAddress

from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required




# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect ('home:index')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('accounts:success')
            else:
                messages.error(request, "Error")

    context ={
        'form':form
    }
    return render(request, 'accounts/register.htm',context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect ('home:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request,username=username, password=password)

            if username and password != '':
                if user is not None:
                    login(request,user)
                    return redirect('home:index')
                else:
                    messages.info(request, "*Username or password is incorrect")
            else:
                messages.info(request, "*Enter username and password")

        context={

        }
    return render(request, "accounts/login.htm")

def success(request): 
    return render(request, "accounts/success.htm")

def logoutUser(request):
    logout(request)
    return redirect('home:index')

def userProfile(request):
    current_user = request.user

    data = User.objects.get(id=current_user.id)
    if UserAddress.objects.filter(user_info_id=current_user.id).exists():
        data2 = UserAddress.objects.get(user_info_id=current_user.id)
    else:
        data2 = "Enter Detail"


    if request.user.is_authenticated:
        if request.method == 'POST':
            user_info_id = request.POST.get('UserId')
            address_name = request.POST.get('address')
            street = request.POST.get('street')
            postalcode = request.POST.get('postalcode')
            city = request.POST.get('city')
            country = request.POST.get('country')

            if address_name and street and postalcode and city and country != '':
                address_data = UserAddress(user_info_id=user_info_id, address=address_name, street=street, postalcode=postalcode, city=city, country= country)
                address_data.save()
                current_user = request.user
                print(f"address saved")
                data2 = UserAddress.objects.get(user_info_id=current_user.id)
            else:
                print("empty")
        context={
            'user': data,
            'address': data2
        }

        return render(request, "accounts/profile.html", context)

accounts/templates/accounts/login.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Login</title>
	<link rel="stylesheet" href="{% static 'accounts/loginstyle.css' %}">
</head>
<body>
	<div class="master">
		<div class="main-container">
			<div class="left-pane"><img src="{% static 'accounts/Elite rental logo.png'%}"></div>
			<div class="right-pane">
				<div class="title">
					<h2>Login</h2>
				</div>

				<div class="entryField">		
					<form method="POST">
							{%csrf_token %}
							<input type="text" name="username" placeholder=Username>
						</div>
						<div class="entryField">		
			
							<input type="password" name="password" placeholder="Password">
						</div>
						<button class="login-btn" type="submit">
							Login
						</button>
					</form>
					<div class="signin">
						Don't have an account? <a href="{% url 'accounts:register' %}">Register</a><br><br>
						{% for message in messages %}
						<p style="color: red;">{{message}}</p>
						{% endfor %}
					</div>
			

			</div>
		</div>
	</div>
</body>
</html>

accounts/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Profile</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/profile.css' %}"> 


</head>
<body>

    <div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href active"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>

    <section id="headingSection">
        <div class="container">
            <center>
            <h1 class="title">User Profile</h1>
            <hr class="sep">
            </center>
        </div>
    </section>

    <section id="profileBox">
        <div class="left-sidebar">
            <div class="container">

            

            <label for="Username">Username:</label>
            <input name="Username" type="text" value={{user.username}} class="inf1"readonly>

            <label for="DateJoin">Date Joined:</label>
            <input name="DateJoin" type="datetime" value="{{user.date_joined}}" class="inf1" readonly>

            <label for="LastLogin">Last Login:</label>
            <input name="LastLogin" type="datetime" value="{{user.last_login}}" class="inf1" readonly>
        </div>
    </div>

        <div class="main-content">
        <div class="container">
            <h1 class="secondaryTitle">Account Information</h1>
            <form method="POST">
                {% csrf_token %}
                <label for="UserId">User Id:</label>
                <input name="Userid" type="text" value={{user.id}} class="inf1"readonly>

                <label for="FirstName">First Name:</label>
                <input name="FirstName" type="text" value={{user.first_name}} class="inf1"  readonly>

                <label for="LastName">Last Name:</label>
                <input name="LastName" type="text" value={{user.last_name}} class="inf1" readonly>

                <label for="Email">Email:</label>
                <input name="Email" type="text" class="inf1"  value={{user.email}} readonly>
                <br>
            <h1 class="secondaryTitle">Address Information</h1>
                    <label for="address">Address:</label>
                    <input name="address" type="text" 

                    {% if address == "Enter Detail"%}
                    placeholder="Enter Address"
                    {% else %}
                    value="{{address.address}}" 
                    readonly
                    {% endif %}

                    class="inf1">

                    <label for="street">Street:</label>
                    <input name="street" type="text" 
                    
                    {% if address == "Enter Detail"%}
                    placeholder="Enter Street"
                    {% else %}
                    value="{{address.street}}" 
                    readonly
                    {% endif %}
                    
                    class="inf1">

                    <label for="postalcode">Postal Code:</label>
                    <input name="postalcode" type="text" 
                    
                    {% if address == "Enter Detail"%}
                    placeholder="Enter Postal Code"
                    {% else %}
                    value={{address.postalcode}} 
                    readonly
                    {% endif %}
                    
                    class="inf1">

                    <label for="city">City:</label>
                    <input name="city" type="text" 
                    
                    {% if address == "Enter Detail"%}
                    placeholder="Enter City"
                    {% else %}
                    value={{address.city}} 
                    readonly
                    {% endif %}
                    
                    class="inf1">

                    <label for="country">Country:</label>
                    <input name="country" type="text" value="Nepal" class="inf1"readonly>
                    {% if address != "Enter Detail"%}
                        <button type="submit" disabled>Save</button>
                    {% else %}
                        <button type="submit">Save</button>
                    {% endif %}
                </form>

        </div>
        </div>
    </section>




<footer class="footer-distributed">
 
    <div class="footer-left">
    
    <h3><span class="highlight">Elite</span>Rental</h3>
    
    <p class="footer-links">
    <a href="">Home</a>
    ·
    <a href="#">Services</a>
    ·
    <a href="#">Contact</a>
    ·
    <a href="#">About</a>
    ·
    <a href="#">Faq</a>

    </p>
    
    <p class="footer-company-name">eliterental &copy; 2021</p>
    </div>
    
    <div class="footer-center">
    
    <div>
    <i class="fa fa-map-marker"></i>
    <p><span>Dillibazar</span> Kathmandu, Nepal</p>
    </div>
    
    <div>
    <i class="fa fa-phone"></i>
    <p>+1 555 123456</p>
    </div>
    
    <div>
    <i class="fa fa-envelope"></i>
    <p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
    </div>
    
    </div>
    
    <div class="footer-right">
    
    <p class="footer-company-about">
    <span>About the company</span>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </p>
    
    <div class="footer-icons">
    
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
    
    </div>
    
    </div>
    
    </footer>


  

</body>
</html>

accounts/templates/accounts/register.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Register</title>
	<link rel="stylesheet" href="{% static 'accounts/register.css' %}">

</head>
<body>

	<div id="container">
		<div class="logoHolder">
			<div class="logo">
				<img src="{%static 'accounts/Elite rental logo.png'%}">
			</div>
		</div>
		<div id="cred-container">
					<div class="sep">
		</div>
			<div class="title">
				<h2>Create an account</h2>
			</div>
			<form action="register" method="POST">
			{% csrf_token %}
			<div class="row1">		
				<div class="col">
					{{form.first_name}}
				</div>
				<div class="col">

					{{form.last_name}}

				</div>
			</div>
			<div class="row2">	
				<div class="col">
					
					{{form.username}}

				</div>
				<div class="col">

					{{form.email}}
				</div>
			</div>
			<div class="row3">		
				<div class="col">

					{{form.password1}}
				</div>
				<div class="col">
					
					{{form.password2}}
				</div>
			</div>
			<div class="row4">
				<input type="Submit" class="register-btn">
				
			</div>
		</form>




		<div class="signin">
			Already have an account? <a href="{% url 'accounts:loginPage' %}">Sign In</a><br><br>

			{% if form.errors %}
    		{% for field in form %}
        		{% for error in field.errors %}
            		<div class="alert alert-danger">
                		<strong style="color: red;">{{ error|escape }}</strong>
            		</div>
        		{% endfor %}
   			{% endfor %}

    		{% for error in form.non_field_errors %}
        		<div class="alert alert-danger">
            		<strong style="color: red;">{{ error|escape }}</strong>
        		</div>
    		{% endfor %}
			{% endif %}

		</div>

		</div>

	</div>
	<script>
		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='FirstName';
		form_fields[2].placeholder='LastName';
		form_fields[3].placeholder='Username';
		form_fields[4].placeholder='Email';
		form_fields[5].placeholder='Password';
		form_fields[6].placeholder='Confirm Password';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

accounts/templates/accounts/success.htm
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #ebe9e9;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #abdd61;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }

      .login-btn{
        margin-top: 25px;
        width: 20%;
        border-radius: 50px;
        background-color: #005789;
        border: 0;
        padding: 15px;
        font-size: 0.9vw;
        color: white;
        font-weight: bold;
        cursor: pointer;
      }
      .login-btn:hover,
      .login-btn:focus {
        box-shadow: 0 1em 1em -0.4em grey;
        transform: translateY(-0.25em);
        transition: 0.3s;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>Account has been created<br/> Please proceed to login page to continue</p>
        <a href="{% url 'accounts:loginPage' %}">
            <button class="login-btn">
                Login
            </button>
        </a>

      </div>
    </body>
</html>