about/urls.py
from django.urls.conf import include
from django.urls import path

from . import views

app_name='about'

urlpatterns = [
    path("", views.about_index, name="about_index")
]

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from django.http import HttpResponse, response

# Create your views here.

def about_index(request):
    return render(request,'about/AboutUs.html')

about/templates/about/AboutUs.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<link rel="stylesheet" type="text/css" href="{% static 'about/about.css' %}"> 
	<title>About Us</title>
</head>


<body>

	<div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="active link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>


	
<section class="services">
	<div class="container">

		

		<h1 class="heading">WELCOME TO ELITE CAR RENTAL </h1>
		<hr class="sep">
		<div class="welcome">
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.x</p>
		</div>




		<hr style="width: 90%; margin-top: 50px;">
		<h1 class="heading">OUR SERVICES</h1>
		<hr class="sep">
		<div class="box-container">
			<div class="boxes">	
				<img src="{% static 'about/book.jpg'%}">
				<h3>Book Online</h3>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
			</div>

			<div class="boxes">	
				<img src="{% static 'about/phone.jpg'%}">
				<h3>Book Over Phone</h3>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
			</div>


			<div class="boxes">	
				<img src="{% static 'about/happy.png'%}">
				<h3>Happy Customers</h3>
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
			</div>
		</div>

	</div>
	
</section>

<footer class="footer-distributed">
 
	<div class="footer-left">
	
	<h3><span class="highlight">Elite</span>Rental</h3>
	
	<p class="footer-links">
	<a href="">Home</a>
	·
	<a href="#">Services</a>
	·
	<a href="#">Contact</a>
	·
	<a href="#">About</a>
	·
	<a href="#">Faq</a>

	</p>
	
	<p class="footer-company-name">eliterental &copy; 2021</p>
	</div>
	
	<div class="footer-center">
	
	<div>
	<i class="fa fa-map-marker"></i>
	<p><span>Dillibazar</span> Kathmandu, Nepal</p>
	</div>
	
	<div>
	<i class="fa fa-phone"></i>
	<p>+1 555 123456</p>
	</div>
	
	<div>
	<i class="fa fa-envelope"></i>
	<p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
	</div>
	
	</div>
	
	<div class="footer-right">
	
	<p class="footer-company-about">
	<span>About the company</span>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit.
	</p>
	
	<div class="footer-icons">
	
	<a href="#"><i class="fa fa-facebook"></i></a>
	<a href="#"><i class="fa fa-twitter"></i></a>
	<a href="#"><i class="fa fa-linkedin"></i></a>
	<a href="#"><i class="fa fa-github"></i></a>
	
	</div>
	
	</div>
	
	</footer>
	




	


</body>
</html>