services/urls.py
from django.urls import path


from . import views

app_name='services'

urlpatterns = [
    path("", views.index, name="index"),
    path("cars", views.display, name="display"),
    path('detail/<int:car_id>', views.detail, name="detail"),
    path('booking', views.booking, name="booking"),
    path('payment', views.payment, name="payment"),
]

services/templates/services/book.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Booking</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'services/bookStyle.css' %}"> 


</head>
<body>

    <div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="active link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>
    <div class="tb-container">
        <h1 class="title">Booking History</h1>
        <hr class="sep">
        <table>
            <thead>
              <tr>
                <th scope="col">Vehicle</th>
                <th scope="col">PickUp Date</th>
                <th scope="col">PickUp Address</th>
                <th scope="col">PickUp Time</th>
                <th scope="col">DropUp Date</th>
                <th scope="col">DropUp Address</th>
                <th scope="col">PickUp Time</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            {% for hist in history%}
            <tbody>
              <tr>
                <td data-label="Vehicle">
                    <div class="img-container">
                        {% for i in img %}
                            {% if hist.car_id_id == i.id %}
                               <a href="/services/detail/{{hist.car_id_id}}?{{i.brand}}{{i.name}}"> <img src="{{i.vehicleImage.url}}" alt="{{i.name}}"> </a> 
                            {% endif %}
                        {% endfor %}
                    </div>
                </td>
                <td data-label="PickDate">{{hist.pickDate}}</td>
                <td data-label="PickAddress">{{hist.pickAddress}}</td>
                <td data-label="PickTime">{{hist.pickTime}}</td>
                <td data-label="DropDate">{{hist.dropDate}}</td>
                <td data-label="DropAddress">{{hist.dropAddress}}</td>
                <td data-label="DropTime">{{hist.dropTime}}</td>
                <div>
                <td data-label="Status">
                    {% if hist.status == "Processing" %}
                        <h4 class="st processing"> {{hist.status}}</h4> 
                    {% elif hist.status == "Cancelled" %}
                        <h4 class="st cancelled"> {{hist.status}}</h4> 
                    {% elif hist.status == "Booked" %}
                        <h4 class="st booked"> {{hist.status}}</h4> 
                        {% elif hist.status == "Done" %}
                        <h4 class="st done"> {{hist.status}}</h4> 
                    {% endif %}
                </td>
                </div>
              </tr>
              
            </tbody>
            {% endfor %}
        </table>
    </div>


    <footer class="footer-distributed">
 
        <div class="footer-left">
        
        <h3><span class="highlight">Elite</span>Rental</h3>
        
        <p class="footer-links">
        <a href="">Home</a>
        ·
        <a href="#">Services</a>
        ·
        <a href="#">Contact</a>
        ·
        <a href="#">About</a>
        ·
        <a href="#">Faq</a>
    
        </p>
        
        <p class="footer-company-name">eliterental &copy; 2021</p>
        </div>
        
        <div class="footer-center">
        
        <div>
        <i class="fa fa-map-marker"></i>
        <p><span>Dillibazar</span> Kathmandu, Nepal</p>
        </div>
        
        <div>
        <i class="fa fa-phone"></i>
        <p>+1 555 123456</p>
        </div>
        
        <div>
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
        </div>
        
        </div>
        
        <div class="footer-right">
                    
        <p class="footer-company-about">
        <span>About the company</span>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        </p>
        
        <div class="footer-icons">
        
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
        
        </div>
        
        </div>
        
        </footer>


    


  

</body>
</html>
	

services/templates/services/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>{{car_pk.name}}</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'services/detail.css' %}"> 


</head>
<body>

    <div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="active link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>



    <section id="showcase">
        <div class="container">
            <img src="{{car_pk.vehicleImage.url}}" class="img-fluid">
        </div>
    </section>


<div class="main-container">
    <div class="panel1">
        <h1 class="title">{{car_pk.brand}} {{car_pk.name}}</h1>
        <h6>{{review_count}} Reviews</h6>
        <hr class="dash-hr">  
        <div class="ft-container">
            <div class="ft">
                <img src="{% static 'services/avatar.png' %}"><span>{{car_pk.passenger}} Passenger</span>
            </div>
            <div class="ft">
                <img src="{% static 'services/pump.png' %}"><span>{{car_pk.carFuel}}</span>
            </div>
             <div class="ft">
                 <img src="{% static 'services/settings.png' %}"><span> {{car_pk.transmission}}</span>
            </div>
            <div class="ft">
                <img src="{% static 'services/boot.png' %}"><span> {{car_pk.bootCapacity}} litres </span>
            </div>
        </div>
        <hr class="dash-hr">    
        <h5 class="sub-title">Included</h5>
        <div class="full-ft-container">  
            {% for feature in car_pk.features %}
            <div class="s-ft">✔ {{feature}}</div>
            {% endfor %}
        </div>   
        <hr class="large-sep">
        <h5 class="sub-title">Reviews</h5>

        <!-- need loop -->
        {% for uR in review_car %}
            
            <div class="review">
                <div class="picture-panel">
                    <div class="profile-pic">
                        <img src="{% static 'services/rv-img.png' %}" alt="">
                    </div>
                </div>
                <div class="text-panel">
                    <div class="name-dt">
                        <h4 class="tp-n">{{uR.name}}</h4>
                        <h5 class="tp-dt">{{uR.timeStamp}}</h5>
                    </div>
                    <div class="rv">
                        <p>{{uR.message}}</p>
                    </div>
                </div>
            </div>
            <hr class="dash-hr">
        {% endfor %}
        <!-- end loop -->


        <h5 class="sub-title">Write a Review</h5>
        <div class="reviewForm-container">
    
            <h5 class="form-label forRV">Message</h5>
            <form method="POST" action="/services/detail/{{car_pk.id}}">
                {% csrf_token %}
            <textarea class="form-entry msg" type="message" name="message"></textarea>
            <div class="divided">
                <div class="i-f1">
                    <h5 class="form-label forRV">Full Name</h5>
                    <input class="review-entry" type="text" name="fullname">
                </div>
                <div class="i-f2">
                    <h5 class="form-label forRV">Email Address</h5>
                    <input class="review-entry" type="email" name="email">
                </div>
                <div class="row btn-p">
                    <button class="btn post" name="SendReview"> Post Review</button>
                </div>
            </div>
        </form>  


            
        </div>   
    </div>




    <div class="panel2">

    <div class="book-form">
        <div class="p-cont">
            <h1> <span>Rs</span>{{car_pk.price}}</h1>
                    <h5 class="d-f">Per Day</h5>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="column">
    
                <div class="row">
                    <h5 class="form-label">Full Name</h5>
                    <input class="form-entry" type="text" name="name" placeholder="Emily Clarke">
                </div>
                <div class="row">
                    <h5 class="form-label">Email Address</h5>
                    <input class="form-entry" type="email" name="email" placeholder="example@email.com">
                </div>
                <div class="row">
                    <h5 class="form-label">Phone Number</h5>
                    <input class="form-entry" type="text" name="phone" placeholder="9841000000">
                </div>
                <div class="row">
                    <h5 class="form-label">Pickup Address</h5>
                    <input class="form-entry date" type="text" name="pickupAddress" placeholder="Kamalbinayak, Bhaktapur">
                </div>
                <div class="row">
                    <h5 class="form-label">Pickup Date</h5>
                    <input class="form-entry date" type="date" name="pickupDate">
                </div>
                <div class="row">
                    <h5 class="form-label">Pickup Time</h5>
                    <input class="form-entry" type="time" name="pickupTime">
                </div>
                <div class="row">
                    <h5 class="form-label">Drop Off Address</h5>
                    <input class="form-entry" type="text" name="dropAddress" placeholder="Softwarica College, Dillibazar">
                </div>
                <div class="row">
                    <h5 class="form-label">Drop Off Date</h5>
                    <input class="form-entry" type="date" name="dropDate">
                </div>
                <div class="row">
                    <h5 class="form-label">Drop Off Time</h5>
                    <input class="form-entry" type="time" name="dropTime">
                </div>
                {% if user.is_authenticated %}
                    <div class="row btn-c">
                        <button class="btn" type="submit" name="Callback">Request Callback</button>
                    </div>
                    <hr class="sep">
                    <div class="row btn-c">
                        <button class="btn book" type="submit" name="BookInstantly">Book Instantly</button>
                    </div>
                {% else %}
                    <div class="row btn-c">
                        <button class="btn" type="submit" name="Callback" disabled>Request Callback</button>
                    </div>
                    <hr class="sep">
                    <div class="row btn-c">
                        <button class="btn book" type="submit" name="BookInstantly" disabled>Book Instantly</button>
                    </div>
                    <h4 style="color: red; margin-top: 7px; font-weight: 600;">*Please Login to rent vehicle</h4><br>
                {% endif %}
            
            </div>  
        </form>
    </div>
    
    </div>
</div>
    




<footer class="footer-distributed">
 
    <div class="footer-left">
    
    <h3><span class="highlight">Elite</span>Rental</h3>
    
    <p class="footer-links">
    <a href="">Home</a>
    ·
    <a href="#">Services</a>
    ·
    <a href="#">Contact</a>
    ·
    <a href="#">About</a>
    ·
    <a href="#">Faq</a>

    </p>
    
    <p class="footer-company-name">eliterental &copy; 2021</p>
    </div>
    
    <div class="footer-center">
    
    <div>
    <i class="fa fa-map-marker"></i>
    <p><span>Dillibazar</span> Kathmandu, Nepal</p>
    </div>
    
    <div>
    <i class="fa fa-phone"></i>
    <p>+1 555 123456</p>
    </div>
    
    <div>
    <i class="fa fa-envelope"></i>
    <p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
    </div>
    
    </div>
    
    <div class="footer-right">
    			
    <p class="footer-company-about">
    <span>About the company</span>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </p>
    
    <div class="footer-icons">
    
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
    
    </div>
    
    </div>
    
    </footer>


  

</body>
</html>
	

services/templates/services/display.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Services</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'services/displayStyle.css' %}"> 


</head>
<body>

    <div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="active link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>


    <section id="headingSection">
        <div class="container">
            <center>
            <h1 class="title">{{category_name}}</h1>
            <hr class="sep">
            </center>
        </div>
    </section>

    <section id="typeBox">
       <div class="container">

        {% for info in vehicle_info  %}
            <div class="row">  
                <div class="card">
                    <a href="/services/detail/{{info.id}}?{{info.brand}}{{info.name}}">
                        <img src={{info.vehicleImage.url}}>
                    </a>
                </div>
                
            </div>
            
            <div class="info-row">  
                <div class="left-wrapper">
                    <h3 class="info-text">{{info.brand}} {{info.name}}</h3>
                    <div class="feature-wrapper">
                        <img src="{% static 'services/avatar.png' %}">
                        <img src="{% static 'services/pump.png' %}">
                        <img src="{% static 'services/settings.png' %}">
                    </div>
                    <div class="featureNum-wrapper">
                        <h6>{{info.passenger}}</h6>
                        <h6>{{info.carFuel}}</h6>
                        <h6 class="bring-left">{{info.transmission}}</h6>

                    </div>                
                    </div>

                    <div class="right-wrapper">
                        <div class="info-price"><span style="font-size: 16px;">Rs</span>{{info.price}}</div>
                        <div class="info-perday">Per Day</div>
                    </div>
            </div>
                    <div class="lower-pane">
                        <div class="ava-wrapper">
                        <h4>Available:
                            {% if info.availability == "Yes" %}
                                <div class="img-wrp">
                                    <img class = "yesImg" src ="{% static 'services/yes.png' %}">
                                </div>
                            {% else %}
                                <div class="img-wrp">
                                    <img class = "yesImg" src ="{% static 'services/no.png' %}">
                                </div>
                            {% endif %}

                        </h4>
                    </div>
                    <a href="/services/detail/{{info.id}}?{{info.brand}}{{info.name}}"><button class="detail-btn">Detail</button></a>
                </div>
                    
                
        {% endfor %}
        </div>

    </section>

    




<footer class="footer-distributed">
 
    <div class="footer-left">
    
    <h3><span class="highlight">Elite</span>Rental</h3>
    
    <p class="footer-links">
    <a href="">Home</a>
    ·
    <a href="#">Services</a>
    ·
    <a href="#">Contact</a>
    ·
    <a href="#">About</a>
    ·
    <a href="#">Faq</a>

    </p>
    
    <p class="footer-company-name">eliterental &copy; 2021</p>
    </div>
    
    <div class="footer-center">
    
    <div>
    <i class="fa fa-map-marker"></i>
    <p><span>Dillibazar</span> Kathmandu, Nepal</p>
    </div>
    
    <div>
    <i class="fa fa-phone"></i>
    <p>+1 555 123456</p>
    </div>
    
    <div>
    <i class="fa fa-envelope"></i>
    <p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
    </div>
    
    </div>
    
    <div class="footer-right">
    			
    <p class="footer-company-about">
    <span>About the company</span>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </p>
    
    <div class="footer-icons">
    
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
    
    </div>
    
    </div>
    
    </footer>


  

</body>
</html>
	

services/templates/services/payment.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Payment</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'services/paymentStyle.css' %}"> 


</head>
<body>
    <div class="card">
        <div class="upper-pane">
            <div class="left">
                <div class="row -c">
                    <h2>Booking Payment Detail</h2>
                </div>
                <div class="row">
                    <h3 class="info">Username: {{current_user}}</h3>
                </div>
                <div class="row">
                    <h3 class="info">Booking ID: {{payment_info.book_id}}</h3>
                </div>
                <div class="row">
                    {% for i in info %}
                        {% if payment_info.car_id == i.id %}
                            <h3 class="info">Vehicle Name: {{i.name}}</h3>
                        {% endif %}
                    {% endfor %} 
                </div>
                <div class="row">
                    <h3 class="info">Status: {{payment_info.status}}</h3>
                </div>
            </div>
            <div class="right">
                <img class="QR" src="{% static 'services/paymentQR.jpg' %}">
            </div>
            
        </div>
    </div>
    <div class="lower-pane">
        <p>*Please use scan pay for payment. Enter the booking payment detail in the remarks during payment</p>
        <p>*The payment gets confirmed within the day of payment itself, please look into your booking history to check status of booking</p>
        <a href="{% url 'services:booking' %}"><button class="btn">Booking History</button></a>
    </div>
</body>
</html>
	

services/templates/services/services.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Services</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'services/services.css' %}"> 


</head>
<body>

    <div class="nav-bar">
        <div class="nav-logo">
            <h1>
            <span class="highlight">Elite</span>Rental
        </h1></div>
        <div class="nav-link">
            
            <nav>
				<ul>
					<li><a class="link-href" href="{% url 'home:index' %}">Home</a></li>
					<li><a class="active link-href" href="{% url 'services:index' %}">Cars</a></li>
					<li><a class="link-href" href="{% url 'about:about_index' %}">About</a></li>
					<li><a class="link-href" href="{% url 'contact:contact_index' %}">Contact</a></li>
					<li><a class="link-href" href="{% url 'faq:faq_index' %}">FAQ</a></li>
				</ul>
			</nav>
        </div>

        <div class="p-f">
            <div>
            {% if user.is_authenticated %}
                <li><a class="link-href" href="{% url 'services:booking' %}">Booking</a></li>
                <li><a class="img-hover link-href"   href="{% url 'accounts:profile' %}"><img src="{% static 'home/user-24.png' %}"></a></li>
                <li><a class="img-hover link-href" href="{% url 'accounts:logout' %}"><img src="{% static 'home/logout-24.png' %}"></a></li>
            {% else %}
                <li style="color:yellow;"><a href="{% url 'accounts:loginPage' %}">Login</a></li>
            {% endif %}
            </div>
        </div>
    </div>

    <section id="headingSection">
        <div class="container">
            <center>
            <h1 class="title">Find car by type</h1>
            <hr class="sep">
            </center>
        </div>
    </section>

    <section id="typeBox">
       <div class="container">

       	<!-- row1 -->
       	<div class="row">
    <div class="card">
        
            <h3 class="img-text">Sedan</h3>
            <a href="{% url 'services:display' %}?category=1">
                <img src="{% static 'services/Sedan.jpg' %}">
            </a>
    </div>
    <div class="card">
    	<h3 class="img-text">SUV</h3>
    	<a href="{% url 'services:display' %}?category=2"><img src="{% static 'services/suv.jpg' %}"></a>
    </div>
    <div class="card">
    	<h3 class="img-text">4 Wheel</h3>
    	<a href="{% url 'services:display' %}?category=6"><img src="{% static 'services/4wheel.jpg' %}"></a>
    </div>
</div>

      	<!-- row2 -->
       	<div class="row">
    <div class="card">
    	<h3 class="img-text">Electric</h3>
    	<a href="{% url 'services:display' %}?category=4"><img src="{% static 'services/electric.jpg' %}"></a>
    </div>
    <div class="card">
    	<h3 class="img-text">Pick-up</h3>
    	<a href="{% url 'services:display' %}?category=3"><img src="{% static 'services/pick-up.jpg' %}"></a>
    </div>
    <div class="card">
    	<h3 class="img-text">Vans</h3>
    	<a href="{% url 'services:display' %}?category=5"><img src="{% static 'services/van.jpg' %}"></a>
    </div>
</div>
    </section>


    




<footer class="footer-distributed">
 
    <div class="footer-left">
    
    <h3><span class="highlight">Elite</span>Rental</h3>
    
    <p class="footer-links">
    <a href="">Home</a>
    ·
    <a href="#">Services</a>
    ·
    <a href="#">Contact</a>
    ·
    <a href="#">About</a>
    ·
    <a href="#">Faq</a>

    </p>
    
    <p class="footer-company-name">eliterental &copy; 2021</p>
    </div>
    
    <div class="footer-center">
    
    <div>
    <i class="fa fa-map-marker"></i>
    <p><span>Dillibazar</span> Kathmandu, Nepal</p>
    </div>
    
    <div>
    <i class="fa fa-phone"></i>
    <p>+1 555 123456</p>
    </div>
    
    <div>
    <i class="fa fa-envelope"></i>
    <p><a href="mailto:support@company.com">contact@eliterental.com</a></p>
    </div>
    
    </div>
    
    <div class="footer-right">
    			
    <p class="footer-company-about">
    <span>About the company</span>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </p>
    
    <div class="footer-icons">
    
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
    
    </div>
    
    </div>
    
    </footer>


  

</body>
</html>
	